name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Test
        run: go test ./...

  containerize:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        if: ${{ ! startsWith(github.event_name, 'pull_request') }}
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USER }}
          password: ${{ secrets.PACKAGE_SCOPE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        if: ${{ ! startsWith(github.event_name, 'pull_request') }}
        with:
          aws-access-key-id: ${{ secrets.ECR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.ECR_AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        if: ${{ ! startsWith(github.event_name, 'pull_request') }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: |
            ghcr.io/bloodhoundad/azurehound
            ${{ steps.login-ecr.outputs.registry || 'public.ecr.aws' }}/production/azurehound
          tags: |
            type=edge,branch=main
            type=sha,prefix=edge-,format=short
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Container Image
        uses: docker/build-push-action@v6
        with:
          context: .
          build-args: VERSION=v0.0.0-rolling+${{ github.sha }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: false
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.PACKAGE_SCOPE }}
          # Multi-plaform builds can not be loaded into local Docker Daemon 
          # Must use an Open Container Image to scan for vulnerabilities.
          outputs: type=oci,dest=/tmp/oci-image.tar

      - name: Upload OCI tarball
        uses: actions/upload-artifact@v4
        with:
          name: oci-image-tar
          path: /tmp/oci-image.tar

      # Convert OCI Directory to Docker-compatible tars for amd64 and arm64
      - name: Convert OCI to Docker tarballs (amd64 + arm64)
        run: |
          set -euo pipefail
          for arch in amd64 arm64; do
            echo "Converting $arch image..."

            if ! skopeo copy \
              --override-arch=$arch --override-os=linux \
              oci-archive:/tmp/oci-image.tar \
              docker-archive:/tmp/converted-$arch.tar; then
              echo "skopeo copy failed for $arch"
              exit 1
            fi
          done

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        os:
          - darwin
          - linux
          - windows
        arch:
          - amd64
          - arm64
    steps:
      - uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          check-latest: true
          cache: true

      - name: Build
        run: 'go build -ldflags="-s -w -X github.com/bloodhoundad/azurehound/v2/constants.Version=v0.0.0-rolling+${{ github.sha }}"'
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}

      - name: Zip
        if: "! startsWith(github.event_name, 'pull_request')"
        run: 7z a -tzip -mx9 azurehound-${{ matrix.os }}-${{ matrix.arch }}.zip azurehound*

      - name: Compute Checksum
        if: "! startsWith(github.event_name, 'pull_request')"
        run: sha256sum azurehound-${{ matrix.os }}-${{ matrix.arch }}.zip > azurehound-${{ matrix.os }}-${{ matrix.arch }}.zip.sha256

      - name: Update Rolling Release
        if: "! startsWith(github.event_name, 'pull_request')"
        uses: softprops/action-gh-release@v1
        with:
          name: Rolling Release (unstable)
          tag_name: rolling
          prerelease: true
          files: |
            azurehound-${{ matrix.os }}-${{ matrix.arch }}.zip
            azurehound-${{ matrix.os }}-${{ matrix.arch }}.zip.sha256
          body: |
            Rolling release of AzureHound compiled from source (${{ github.sha }})
            This is automatically kept up-to-date with the `${{ github.ref_name }}` ${{ github.ref_type }}
